;------------------------------------------------------------------
; Materia......: Laboratorio de Microcomputadoras.
; Curso........: Campigglio - Stola
; Fecha inicio.: 14/03/2016
; Fecha entrega: 20/06/2016
; Autores......: 
;		 Ezequiel Martín Zarza
;		 Santiago Roman
;		 Federico Verstraeten
;                
; Contacto.....: 
;		 ezequielm.zarza@gmail.com 
;		 santiago_roman@outlook.com	
;		 federico.verstraeten@gmail.com 
;                
;------------------------------------------------------------------
;	REGISTER_ALIAS
;------------------------------------------------------------------
;
;	Definición de alias (.DEF) de cada uno de los registros
;	utilizados en la implementación.
;
;------------------------------------------------------------------

	.def	test1	=	r0		; Definicion de prueba 0
	.def    test2  	=   r1		; Definicion de prueba 1
	
